title: Parhan
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://parhan.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
 # - title: Contact
  #  url: /contact

social:
  github:
  twitter: rohitag88  
  facebook: rohitagarwal88
  email: rohit_agarwal@live.in

google_analytics: ""

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
  - support-for
